### ISSUE TITLE
deprecated Node.js version and will be forced to run on node20

### ISSUE THREAD

**Issue by rkorebrits-paystack** [emilioschepis/wait-for-endpoint#4]
Hi, are you able to fix this?

> The following actions use a deprecated Node.js version and will be forced to run on node20: `emilioschepis/wait-for-endpoint@v1.0.3`. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by emilioschepis** [comment]
Hi @rkorebrits-paystack , I just pushed a tag to update the version to Node.js 20! Upgrade to v1.0.4 and let me know if you find any issues.
